"use client";

import Link from "next/link";
import { ReactNode, useEffect, useState } from "react";

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Account = { id: string; display_name: string; environment: "DEMO" | "LIVE"; lifecycle_status: string; bot_state: string; execution_mode: string };
const links = [["⌂", "Dashboard", "/"], ["⌁", "Markets", "/markets"], ["◇", "Opportunities", "/opportunities"], ["▣", "Positions", "/positions"], ["◈", "Strategies", "/strategies"], ["⚙", "System", "/system"]] as const;
function accountQuery(id: string) { return id ? `?account=${encodeURIComponent(id)}` : ""; }

export function OperatorShell({ children }: { children: ReactNode }) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [selected, setSelected] = useState(""); const [emergencyOpen, setEmergencyOpen] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const saved = window.localStorage.getItem("selected-broker-account") ?? ""; setSelected(saved); fetch(`${apiBase}/api/v1/broker-accounts`).then(r => r.ok ? r.json() : Promise.reject()).then(value => { const available = (value.accounts ?? []) as Account[]; setAccounts(available); if (saved && !available.some(account => account.id === saved)) setSelected(""); }).catch(() => setAccounts([])); }, []);
  function chooseAccount(value: string) { setSelected(value); if (value) window.localStorage.setItem("selected-broker-account", value); else window.localStorage.removeItem("selected-broker-account"); }
  async function emergency(kind: "STOP_ONLY" | "CLOSE_ALL") { if (!accounts.length) return; const response = await fetch(`${apiBase}/api/v1/global-emergency`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": `dashboard-${Date.now()}` }, body: JSON.stringify({ account_ids: accounts.map(a => a.id), kind, reason: "Tindakan darurat operator" }) }); setMessage(response.ok ? "Diproses — status final mengikuti operasi darurat." : "Perintah darurat ditolak oleh backend."); setEmergencyOpen(false); }
  const query = accountQuery(selected); const selectedAccount = accounts.find(a => a.id === selected);
  return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">T</span><span>TRADING<br/><strong>ENGINE</strong></span></Link><div className="sidebar-label">WORKSPACE</div><nav className="side-nav" aria-label="Navigasi operator">{links.map(([icon, label, href]) => <Link key={label} href={`${href}${query}`} className={href === "/" ? "active" : ""}><span className="nav-icon">{icon}</span>{label}</Link>)}</nav><div className="sidebar-footer"><span className="status-dot"/> Sistem operasional</div></aside><div className="app-content"><header className="topbar" aria-label="Konteks operator"><div className="mobile-brand"><span className="brand-mark">T</span> Trading Engine</div><label className="account-picker"><span className="muted-label">AKUN AKTIF</span><select aria-label="selected account" value={selected} onChange={e => chooseAccount(e.target.value)}><option value="">Ringkasan Semua Akun</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.display_name} · {a.environment}</option>)}</select></label><div className="topbar-spacer"/><span className="connection"><span className="status-dot"/> LIVE DATA <small>Just now</small></span>{selected && <span data-testid="account-context" className={`env-badge ${selectedAccount?.environment === "LIVE" ? "live" : "demo"}`}>{selectedAccount?.environment ?? ""}</span>}<button className="emergency-button" type="button" aria-label="Emergency" onClick={() => setEmergencyOpen(true)}>♢ Emergency</button>{emergencyOpen && <aside className="dialog" role="dialog" aria-label="Konfirmasi darurat"><div className="dialog-icon">!</div><h2>Emergency control</h2><p>Hentikan exposure sesuai scope akun yang dipilih. Tindakan ini diproses oleh backend.</p><button type="button" onClick={() => emergency("STOP_ONLY")}>Stop exposure <small>Hentikan entry baru</small></button><button type="button" onClick={() => emergency("CLOSE_ALL")}>Stop + close all <small>Hentikan dan tutup posisi</small></button><button type="button" onClick={() => setEmergencyOpen(false)}>Batal</button></aside>}{message && <p className="toast" role="status">{message}</p>}</header>{children}<nav className="mobile-nav" aria-label="Navigasi mobile">{links.slice(0, 4).map(([icon, label, href]) => <Link key={label} href={`${href}${query}`}><span>{icon}</span>{label}</Link>)}<Link href={`/strategies${query}`}><span>•••</span>Lainnya</Link></nav></div></div>;
}
